//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Temporary_Prison.Business.PrisonServices {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PrisonServices.IPrisonService")]
    public interface IPrisonService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrisonService/GetPrisoner", ReplyAction="http://tempuri.org/IPrisonService/GetPrisonerResponse")]
        object GetPrisoner();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrisonService/GetPrisoner", ReplyAction="http://tempuri.org/IPrisonService/GetPrisonerResponse")]
        System.Threading.Tasks.Task<object> GetPrisonerAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPrisonServiceChannel : Temporary_Prison.Business.PrisonServices.IPrisonService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PrisonServiceClient : System.ServiceModel.ClientBase<Temporary_Prison.Business.PrisonServices.IPrisonService>, Temporary_Prison.Business.PrisonServices.IPrisonService {
        
        public PrisonServiceClient() {
        }
        
        public PrisonServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PrisonServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PrisonServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PrisonServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public object GetPrisoner() {
            return base.Channel.GetPrisoner();
        }
        
        public System.Threading.Tasks.Task<object> GetPrisonerAsync() {
            return base.Channel.GetPrisonerAsync();
        }
    }
}
