//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Temporary_Prison.Data.PrisonService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PrisonerDto", Namespace="http://schemas.datacontract.org/2004/07/Temporary_Prison.Service.Contracts.Dto")]
    [System.SerializableAttribute()]
    public partial class PrisonerDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdditionalInformationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime BirthDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] PhoneNumbersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhotoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PlaceOfWorkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PrisonerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RelationshipStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SurnameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AdditionalInformation {
            get {
                return this.AdditionalInformationField;
            }
            set {
                if ((object.ReferenceEquals(this.AdditionalInformationField, value) != true)) {
                    this.AdditionalInformationField = value;
                    this.RaisePropertyChanged("AdditionalInformation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime BirthDate {
            get {
                return this.BirthDateField;
            }
            set {
                if ((this.BirthDateField.Equals(value) != true)) {
                    this.BirthDateField = value;
                    this.RaisePropertyChanged("BirthDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] PhoneNumbers {
            get {
                return this.PhoneNumbersField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneNumbersField, value) != true)) {
                    this.PhoneNumbersField = value;
                    this.RaisePropertyChanged("PhoneNumbers");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Photo {
            get {
                return this.PhotoField;
            }
            set {
                if ((object.ReferenceEquals(this.PhotoField, value) != true)) {
                    this.PhotoField = value;
                    this.RaisePropertyChanged("Photo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PlaceOfWork {
            get {
                return this.PlaceOfWorkField;
            }
            set {
                if ((object.ReferenceEquals(this.PlaceOfWorkField, value) != true)) {
                    this.PlaceOfWorkField = value;
                    this.RaisePropertyChanged("PlaceOfWork");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PrisonerId {
            get {
                return this.PrisonerIdField;
            }
            set {
                if ((this.PrisonerIdField.Equals(value) != true)) {
                    this.PrisonerIdField = value;
                    this.RaisePropertyChanged("PrisonerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RelationshipStatus {
            get {
                return this.RelationshipStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.RelationshipStatusField, value) != true)) {
                    this.RelationshipStatusField = value;
                    this.RaisePropertyChanged("RelationshipStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Surname {
            get {
                return this.SurnameField;
            }
            set {
                if ((object.ReferenceEquals(this.SurnameField, value) != true)) {
                    this.SurnameField = value;
                    this.RaisePropertyChanged("Surname");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataErrorDto", Namespace="http://schemas.datacontract.org/2004/07/Temporary_Prison.Service.Contracts.Dto")]
    [System.SerializableAttribute()]
    public partial class DataErrorDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorDetailsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorDetails {
            get {
                return this.ErrorDetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorDetailsField, value) != true)) {
                    this.ErrorDetailsField = value;
                    this.RaisePropertyChanged("ErrorDetails");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RegistrationOfDetentionDto", Namespace="http://schemas.datacontract.org/2004/07/Temporary_Prison.Service.Contracts.Dto")]
    [System.SerializableAttribute()]
    public partial class RegistrationOfDetentionDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateOfArrivalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateOfDetentionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Temporary_Prison.Data.PrisonService.EmployeeDto DeliveredEmployeeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Temporary_Prison.Data.PrisonService.EmployeeDto DetainedEmployeeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PlaceofDetentionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PrisonerIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateOfArrival {
            get {
                return this.DateOfArrivalField;
            }
            set {
                if ((this.DateOfArrivalField.Equals(value) != true)) {
                    this.DateOfArrivalField = value;
                    this.RaisePropertyChanged("DateOfArrival");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateOfDetention {
            get {
                return this.DateOfDetentionField;
            }
            set {
                if ((this.DateOfDetentionField.Equals(value) != true)) {
                    this.DateOfDetentionField = value;
                    this.RaisePropertyChanged("DateOfDetention");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Temporary_Prison.Data.PrisonService.EmployeeDto DeliveredEmployee {
            get {
                return this.DeliveredEmployeeField;
            }
            set {
                if ((object.ReferenceEquals(this.DeliveredEmployeeField, value) != true)) {
                    this.DeliveredEmployeeField = value;
                    this.RaisePropertyChanged("DeliveredEmployee");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Temporary_Prison.Data.PrisonService.EmployeeDto DetainedEmployee {
            get {
                return this.DetainedEmployeeField;
            }
            set {
                if ((object.ReferenceEquals(this.DetainedEmployeeField, value) != true)) {
                    this.DetainedEmployeeField = value;
                    this.RaisePropertyChanged("DetainedEmployee");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PlaceofDetention {
            get {
                return this.PlaceofDetentionField;
            }
            set {
                if ((object.ReferenceEquals(this.PlaceofDetentionField, value) != true)) {
                    this.PlaceofDetentionField = value;
                    this.RaisePropertyChanged("PlaceofDetention");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PrisonerID {
            get {
                return this.PrisonerIDField;
            }
            set {
                if ((this.PrisonerIDField.Equals(value) != true)) {
                    this.PrisonerIDField = value;
                    this.RaisePropertyChanged("PrisonerID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmployeeDto", Namespace="http://schemas.datacontract.org/2004/07/Temporary_Prison.Service.Contracts.Dto")]
    [System.SerializableAttribute()]
    public partial class EmployeeDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EmployeeIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PositionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SurnameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EmployeeID {
            get {
                return this.EmployeeIDField;
            }
            set {
                if ((this.EmployeeIDField.Equals(value) != true)) {
                    this.EmployeeIDField = value;
                    this.RaisePropertyChanged("EmployeeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Position {
            get {
                return this.PositionField;
            }
            set {
                if ((object.ReferenceEquals(this.PositionField, value) != true)) {
                    this.PositionField = value;
                    this.RaisePropertyChanged("Position");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Surname {
            get {
                return this.SurnameField;
            }
            set {
                if ((object.ReferenceEquals(this.SurnameField, value) != true)) {
                    this.SurnameField = value;
                    this.RaisePropertyChanged("Surname");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReleaseOfPrisonerDto", Namespace="http://schemas.datacontract.org/2004/07/Temporary_Prison.Service.Contracts.Dto")]
    [System.SerializableAttribute()]
    public partial class ReleaseOfPrisonerDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal AccruedAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateOfReleaseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DetentionIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PaidAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Temporary_Prison.Data.PrisonService.EmployeeDto ReleasedEmployeeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal AccruedAmount {
            get {
                return this.AccruedAmountField;
            }
            set {
                if ((this.AccruedAmountField.Equals(value) != true)) {
                    this.AccruedAmountField = value;
                    this.RaisePropertyChanged("AccruedAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateOfRelease {
            get {
                return this.DateOfReleaseField;
            }
            set {
                if ((this.DateOfReleaseField.Equals(value) != true)) {
                    this.DateOfReleaseField = value;
                    this.RaisePropertyChanged("DateOfRelease");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DetentionID {
            get {
                return this.DetentionIDField;
            }
            set {
                if ((this.DetentionIDField.Equals(value) != true)) {
                    this.DetentionIDField = value;
                    this.RaisePropertyChanged("DetentionID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal PaidAmount {
            get {
                return this.PaidAmountField;
            }
            set {
                if ((this.PaidAmountField.Equals(value) != true)) {
                    this.PaidAmountField = value;
                    this.RaisePropertyChanged("PaidAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Temporary_Prison.Data.PrisonService.EmployeeDto ReleasedEmployee {
            get {
                return this.ReleasedEmployeeField;
            }
            set {
                if ((object.ReferenceEquals(this.ReleasedEmployeeField, value) != true)) {
                    this.ReleasedEmployeeField = value;
                    this.RaisePropertyChanged("ReleasedEmployee");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DetentionPagedListDto", Namespace="http://schemas.datacontract.org/2004/07/Temporary_Prison.Service.Contracts.Dto")]
    [System.SerializableAttribute()]
    public partial class DetentionPagedListDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DateOfDetentionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DateOfReleaseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DetentionIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PlaceofDetentionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateOfDetention {
            get {
                return this.DateOfDetentionField;
            }
            set {
                if ((this.DateOfDetentionField.Equals(value) != true)) {
                    this.DateOfDetentionField = value;
                    this.RaisePropertyChanged("DateOfDetention");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateOfRelease {
            get {
                return this.DateOfReleaseField;
            }
            set {
                if ((this.DateOfReleaseField.Equals(value) != true)) {
                    this.DateOfReleaseField = value;
                    this.RaisePropertyChanged("DateOfRelease");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DetentionID {
            get {
                return this.DetentionIDField;
            }
            set {
                if ((this.DetentionIDField.Equals(value) != true)) {
                    this.DetentionIDField = value;
                    this.RaisePropertyChanged("DetentionID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PlaceofDetention {
            get {
                return this.PlaceofDetentionField;
            }
            set {
                if ((object.ReferenceEquals(this.PlaceofDetentionField, value) != true)) {
                    this.PlaceofDetentionField = value;
                    this.RaisePropertyChanged("PlaceofDetention");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DetentionDto", Namespace="http://schemas.datacontract.org/2004/07/Temporary_Prison.Service.Contracts.Dto")]
    [System.SerializableAttribute()]
    public partial class DetentionDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> AccruedAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DateOfArrivalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DateOfDetentionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DateOfReleaseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Temporary_Prison.Data.PrisonService.EmployeeDto DeliveredEmployeeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Temporary_Prison.Data.PrisonService.EmployeeDto DetainedEmployeeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DetentionIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> PaidAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PlaceofDetentionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PrisonerIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Temporary_Prison.Data.PrisonService.EmployeeDto ReleasedEmployeeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> AccruedAmount {
            get {
                return this.AccruedAmountField;
            }
            set {
                if ((this.AccruedAmountField.Equals(value) != true)) {
                    this.AccruedAmountField = value;
                    this.RaisePropertyChanged("AccruedAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateOfArrival {
            get {
                return this.DateOfArrivalField;
            }
            set {
                if ((this.DateOfArrivalField.Equals(value) != true)) {
                    this.DateOfArrivalField = value;
                    this.RaisePropertyChanged("DateOfArrival");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateOfDetention {
            get {
                return this.DateOfDetentionField;
            }
            set {
                if ((this.DateOfDetentionField.Equals(value) != true)) {
                    this.DateOfDetentionField = value;
                    this.RaisePropertyChanged("DateOfDetention");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateOfRelease {
            get {
                return this.DateOfReleaseField;
            }
            set {
                if ((this.DateOfReleaseField.Equals(value) != true)) {
                    this.DateOfReleaseField = value;
                    this.RaisePropertyChanged("DateOfRelease");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Temporary_Prison.Data.PrisonService.EmployeeDto DeliveredEmployee {
            get {
                return this.DeliveredEmployeeField;
            }
            set {
                if ((object.ReferenceEquals(this.DeliveredEmployeeField, value) != true)) {
                    this.DeliveredEmployeeField = value;
                    this.RaisePropertyChanged("DeliveredEmployee");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Temporary_Prison.Data.PrisonService.EmployeeDto DetainedEmployee {
            get {
                return this.DetainedEmployeeField;
            }
            set {
                if ((object.ReferenceEquals(this.DetainedEmployeeField, value) != true)) {
                    this.DetainedEmployeeField = value;
                    this.RaisePropertyChanged("DetainedEmployee");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DetentionID {
            get {
                return this.DetentionIDField;
            }
            set {
                if ((this.DetentionIDField.Equals(value) != true)) {
                    this.DetentionIDField = value;
                    this.RaisePropertyChanged("DetentionID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> PaidAmount {
            get {
                return this.PaidAmountField;
            }
            set {
                if ((this.PaidAmountField.Equals(value) != true)) {
                    this.PaidAmountField = value;
                    this.RaisePropertyChanged("PaidAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PlaceofDetention {
            get {
                return this.PlaceofDetentionField;
            }
            set {
                if ((object.ReferenceEquals(this.PlaceofDetentionField, value) != true)) {
                    this.PlaceofDetentionField = value;
                    this.RaisePropertyChanged("PlaceofDetention");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PrisonerID {
            get {
                return this.PrisonerIDField;
            }
            set {
                if ((this.PrisonerIDField.Equals(value) != true)) {
                    this.PrisonerIDField = value;
                    this.RaisePropertyChanged("PrisonerID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Temporary_Prison.Data.PrisonService.EmployeeDto ReleasedEmployee {
            get {
                return this.ReleasedEmployeeField;
            }
            set {
                if ((object.ReferenceEquals(this.ReleasedEmployeeField, value) != true)) {
                    this.ReleasedEmployeeField = value;
                    this.RaisePropertyChanged("ReleasedEmployee");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PrisonService.IPrisonerService")]
    public interface IPrisonerService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrisonerService/GetPrisonersForPagedList", ReplyAction="http://tempuri.org/IPrisonerService/GetPrisonersForPagedListResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Temporary_Prison.Data.PrisonService.DataErrorDto), Action="http://tempuri.org/IPrisonerService/GetPrisonersForPagedListDataErrorDtoFault", Name="DataErrorDto", Namespace="http://schemas.datacontract.org/2004/07/Temporary_Prison.Service.Contracts.Dto")]
        Temporary_Prison.Data.PrisonService.GetPrisonersForPagedListResponse GetPrisonersForPagedList(Temporary_Prison.Data.PrisonService.GetPrisonersForPagedListRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrisonerService/GetPrisonersForPagedList", ReplyAction="http://tempuri.org/IPrisonerService/GetPrisonersForPagedListResponse")]
        System.Threading.Tasks.Task<Temporary_Prison.Data.PrisonService.GetPrisonersForPagedListResponse> GetPrisonersForPagedListAsync(Temporary_Prison.Data.PrisonService.GetPrisonersForPagedListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrisonerService/GetPrisonerById", ReplyAction="http://tempuri.org/IPrisonerService/GetPrisonerByIdResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Temporary_Prison.Data.PrisonService.DataErrorDto), Action="http://tempuri.org/IPrisonerService/GetPrisonerByIdDataErrorDtoFault", Name="DataErrorDto", Namespace="http://schemas.datacontract.org/2004/07/Temporary_Prison.Service.Contracts.Dto")]
        Temporary_Prison.Data.PrisonService.PrisonerDto GetPrisonerById(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrisonerService/GetPrisonerById", ReplyAction="http://tempuri.org/IPrisonerService/GetPrisonerByIdResponse")]
        System.Threading.Tasks.Task<Temporary_Prison.Data.PrisonService.PrisonerDto> GetPrisonerByIdAsync(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrisonerService/AddPrisoner", ReplyAction="http://tempuri.org/IPrisonerService/AddPrisonerResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Temporary_Prison.Data.PrisonService.DataErrorDto), Action="http://tempuri.org/IPrisonerService/AddPrisonerDataErrorDtoFault", Name="DataErrorDto", Namespace="http://schemas.datacontract.org/2004/07/Temporary_Prison.Service.Contracts.Dto")]
        void AddPrisoner(Temporary_Prison.Data.PrisonService.PrisonerDto prisoner);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrisonerService/AddPrisoner", ReplyAction="http://tempuri.org/IPrisonerService/AddPrisonerResponse")]
        System.Threading.Tasks.Task AddPrisonerAsync(Temporary_Prison.Data.PrisonService.PrisonerDto prisoner);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrisonerService/SearchFilter", ReplyAction="http://tempuri.org/IPrisonerService/SearchFilterResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Temporary_Prison.Data.PrisonService.DataErrorDto), Action="http://tempuri.org/IPrisonerService/SearchFilterDataErrorDtoFault", Name="DataErrorDto", Namespace="http://schemas.datacontract.org/2004/07/Temporary_Prison.Service.Contracts.Dto")]
        Temporary_Prison.Data.PrisonService.PrisonerDto[] SearchFilter(System.Nullable<System.DateTime> dateOfDetention, string name, string address);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrisonerService/SearchFilter", ReplyAction="http://tempuri.org/IPrisonerService/SearchFilterResponse")]
        System.Threading.Tasks.Task<Temporary_Prison.Data.PrisonService.PrisonerDto[]> SearchFilterAsync(System.Nullable<System.DateTime> dateOfDetention, string name, string address);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrisonerService/EditPrisoner", ReplyAction="http://tempuri.org/IPrisonerService/EditPrisonerResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Temporary_Prison.Data.PrisonService.DataErrorDto), Action="http://tempuri.org/IPrisonerService/EditPrisonerDataErrorDtoFault", Name="DataErrorDto", Namespace="http://schemas.datacontract.org/2004/07/Temporary_Prison.Service.Contracts.Dto")]
        void EditPrisoner(Temporary_Prison.Data.PrisonService.PrisonerDto prisoner);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrisonerService/EditPrisoner", ReplyAction="http://tempuri.org/IPrisonerService/EditPrisonerResponse")]
        System.Threading.Tasks.Task EditPrisonerAsync(Temporary_Prison.Data.PrisonService.PrisonerDto prisoner);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrisonerService/DeletePrisoner", ReplyAction="http://tempuri.org/IPrisonerService/DeletePrisonerResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Temporary_Prison.Data.PrisonService.DataErrorDto), Action="http://tempuri.org/IPrisonerService/DeletePrisonerDataErrorDtoFault", Name="DataErrorDto", Namespace="http://schemas.datacontract.org/2004/07/Temporary_Prison.Service.Contracts.Dto")]
        void DeletePrisoner(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrisonerService/DeletePrisoner", ReplyAction="http://tempuri.org/IPrisonerService/DeletePrisonerResponse")]
        System.Threading.Tasks.Task DeletePrisonerAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrisonerService/RegisterDetention", ReplyAction="http://tempuri.org/IPrisonerService/RegisterDetentionResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Temporary_Prison.Data.PrisonService.DataErrorDto), Action="http://tempuri.org/IPrisonerService/RegisterDetentionDataErrorDtoFault", Name="DataErrorDto", Namespace="http://schemas.datacontract.org/2004/07/Temporary_Prison.Service.Contracts.Dto")]
        void RegisterDetention(Temporary_Prison.Data.PrisonService.RegistrationOfDetentionDto registrationOfDetention);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrisonerService/RegisterDetention", ReplyAction="http://tempuri.org/IPrisonerService/RegisterDetentionResponse")]
        System.Threading.Tasks.Task RegisterDetentionAsync(Temporary_Prison.Data.PrisonService.RegistrationOfDetentionDto registrationOfDetention);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrisonerService/ReleaseOfPrisoner", ReplyAction="http://tempuri.org/IPrisonerService/ReleaseOfPrisonerResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Temporary_Prison.Data.PrisonService.DataErrorDto), Action="http://tempuri.org/IPrisonerService/ReleaseOfPrisonerDataErrorDtoFault", Name="DataErrorDto", Namespace="http://schemas.datacontract.org/2004/07/Temporary_Prison.Service.Contracts.Dto")]
        void ReleaseOfPrisoner(Temporary_Prison.Data.PrisonService.ReleaseOfPrisonerDto release);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrisonerService/ReleaseOfPrisoner", ReplyAction="http://tempuri.org/IPrisonerService/ReleaseOfPrisonerResponse")]
        System.Threading.Tasks.Task ReleaseOfPrisonerAsync(Temporary_Prison.Data.PrisonService.ReleaseOfPrisonerDto release);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrisonerService/GetDetentionsByPrisonerIdForPagedList", ReplyAction="http://tempuri.org/IPrisonerService/GetDetentionsByPrisonerIdForPagedListResponse" +
            "")]
        [System.ServiceModel.FaultContractAttribute(typeof(Temporary_Prison.Data.PrisonService.DataErrorDto), Action="http://tempuri.org/IPrisonerService/GetDetentionsByPrisonerIdForPagedListDataErro" +
            "rDtoFault", Name="DataErrorDto", Namespace="http://schemas.datacontract.org/2004/07/Temporary_Prison.Service.Contracts.Dto")]
        Temporary_Prison.Data.PrisonService.GetDetentionsByPrisonerIdForPagedListResponse GetDetentionsByPrisonerIdForPagedList(Temporary_Prison.Data.PrisonService.GetDetentionsByPrisonerIdForPagedListRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrisonerService/GetDetentionsByPrisonerIdForPagedList", ReplyAction="http://tempuri.org/IPrisonerService/GetDetentionsByPrisonerIdForPagedListResponse" +
            "")]
        System.Threading.Tasks.Task<Temporary_Prison.Data.PrisonService.GetDetentionsByPrisonerIdForPagedListResponse> GetDetentionsByPrisonerIdForPagedListAsync(Temporary_Prison.Data.PrisonService.GetDetentionsByPrisonerIdForPagedListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrisonerService/GetDetentionById", ReplyAction="http://tempuri.org/IPrisonerService/GetDetentionByIdResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Temporary_Prison.Data.PrisonService.DataErrorDto), Action="http://tempuri.org/IPrisonerService/GetDetentionByIdDataErrorDtoFault", Name="DataErrorDto", Namespace="http://schemas.datacontract.org/2004/07/Temporary_Prison.Service.Contracts.Dto")]
        Temporary_Prison.Data.PrisonService.DetentionDto GetDetentionById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrisonerService/GetDetentionById", ReplyAction="http://tempuri.org/IPrisonerService/GetDetentionByIdResponse")]
        System.Threading.Tasks.Task<Temporary_Prison.Data.PrisonService.DetentionDto> GetDetentionByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrisonerService/EditDetention", ReplyAction="http://tempuri.org/IPrisonerService/EditDetentionResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Temporary_Prison.Data.PrisonService.DataErrorDto), Action="http://tempuri.org/IPrisonerService/EditDetentionDataErrorDtoFault", Name="DataErrorDto", Namespace="http://schemas.datacontract.org/2004/07/Temporary_Prison.Service.Contracts.Dto")]
        void EditDetention(Temporary_Prison.Data.PrisonService.DetentionDto detention);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrisonerService/EditDetention", ReplyAction="http://tempuri.org/IPrisonerService/EditDetentionResponse")]
        System.Threading.Tasks.Task EditDetentionAsync(Temporary_Prison.Data.PrisonService.DetentionDto detention);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrisonerService/DeleteDetention", ReplyAction="http://tempuri.org/IPrisonerService/DeleteDetentionResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Temporary_Prison.Data.PrisonService.DataErrorDto), Action="http://tempuri.org/IPrisonerService/DeleteDetentionDataErrorDtoFault", Name="DataErrorDto", Namespace="http://schemas.datacontract.org/2004/07/Temporary_Prison.Service.Contracts.Dto")]
        void DeleteDetention(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrisonerService/DeleteDetention", ReplyAction="http://tempuri.org/IPrisonerService/DeleteDetentionResponse")]
        System.Threading.Tasks.Task DeleteDetentionAsync(int id);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetPrisonersForPagedList", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetPrisonersForPagedListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int skip;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int rowSize;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public System.Nullable<System.DateTime> filterByDetainedDate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public System.Nullable<System.DateTime> filterByReleasedDate;
        
        public GetPrisonersForPagedListRequest() {
        }
        
        public GetPrisonersForPagedListRequest(int skip, int rowSize, System.Nullable<System.DateTime> filterByDetainedDate, System.Nullable<System.DateTime> filterByReleasedDate) {
            this.skip = skip;
            this.rowSize = rowSize;
            this.filterByDetainedDate = filterByDetainedDate;
            this.filterByReleasedDate = filterByReleasedDate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetPrisonersForPagedListResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetPrisonersForPagedListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Temporary_Prison.Data.PrisonService.PrisonerDto[] GetPrisonersForPagedListResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int totalCount;
        
        public GetPrisonersForPagedListResponse() {
        }
        
        public GetPrisonersForPagedListResponse(Temporary_Prison.Data.PrisonService.PrisonerDto[] GetPrisonersForPagedListResult, int totalCount) {
            this.GetPrisonersForPagedListResult = GetPrisonersForPagedListResult;
            this.totalCount = totalCount;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDetentionsByPrisonerIdForPagedList", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetDetentionsByPrisonerIdForPagedListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int Id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int skip;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int rowSize;
        
        public GetDetentionsByPrisonerIdForPagedListRequest() {
        }
        
        public GetDetentionsByPrisonerIdForPagedListRequest(int Id, int skip, int rowSize) {
            this.Id = Id;
            this.skip = skip;
            this.rowSize = rowSize;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDetentionsByPrisonerIdForPagedListResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetDetentionsByPrisonerIdForPagedListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Temporary_Prison.Data.PrisonService.DetentionPagedListDto[] GetDetentionsByPrisonerIdForPagedListResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int totalCount;
        
        public GetDetentionsByPrisonerIdForPagedListResponse() {
        }
        
        public GetDetentionsByPrisonerIdForPagedListResponse(Temporary_Prison.Data.PrisonService.DetentionPagedListDto[] GetDetentionsByPrisonerIdForPagedListResult, int totalCount) {
            this.GetDetentionsByPrisonerIdForPagedListResult = GetDetentionsByPrisonerIdForPagedListResult;
            this.totalCount = totalCount;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPrisonerServiceChannel : Temporary_Prison.Data.PrisonService.IPrisonerService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PrisonerServiceClient : System.ServiceModel.ClientBase<Temporary_Prison.Data.PrisonService.IPrisonerService>, Temporary_Prison.Data.PrisonService.IPrisonerService {
        
        public PrisonerServiceClient() {
        }
        
        public PrisonerServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PrisonerServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PrisonerServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PrisonerServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Temporary_Prison.Data.PrisonService.GetPrisonersForPagedListResponse Temporary_Prison.Data.PrisonService.IPrisonerService.GetPrisonersForPagedList(Temporary_Prison.Data.PrisonService.GetPrisonersForPagedListRequest request) {
            return base.Channel.GetPrisonersForPagedList(request);
        }
        
        public Temporary_Prison.Data.PrisonService.PrisonerDto[] GetPrisonersForPagedList(int skip, int rowSize, System.Nullable<System.DateTime> filterByDetainedDate, System.Nullable<System.DateTime> filterByReleasedDate, out int totalCount) {
            Temporary_Prison.Data.PrisonService.GetPrisonersForPagedListRequest inValue = new Temporary_Prison.Data.PrisonService.GetPrisonersForPagedListRequest();
            inValue.skip = skip;
            inValue.rowSize = rowSize;
            inValue.filterByDetainedDate = filterByDetainedDate;
            inValue.filterByReleasedDate = filterByReleasedDate;
            Temporary_Prison.Data.PrisonService.GetPrisonersForPagedListResponse retVal = ((Temporary_Prison.Data.PrisonService.IPrisonerService)(this)).GetPrisonersForPagedList(inValue);
            totalCount = retVal.totalCount;
            return retVal.GetPrisonersForPagedListResult;
        }
        
        public System.Threading.Tasks.Task<Temporary_Prison.Data.PrisonService.GetPrisonersForPagedListResponse> GetPrisonersForPagedListAsync(Temporary_Prison.Data.PrisonService.GetPrisonersForPagedListRequest request) {
            return base.Channel.GetPrisonersForPagedListAsync(request);
        }
        
        public Temporary_Prison.Data.PrisonService.PrisonerDto GetPrisonerById(int Id) {
            return base.Channel.GetPrisonerById(Id);
        }
        
        public System.Threading.Tasks.Task<Temporary_Prison.Data.PrisonService.PrisonerDto> GetPrisonerByIdAsync(int Id) {
            return base.Channel.GetPrisonerByIdAsync(Id);
        }
        
        public void AddPrisoner(Temporary_Prison.Data.PrisonService.PrisonerDto prisoner) {
            base.Channel.AddPrisoner(prisoner);
        }
        
        public System.Threading.Tasks.Task AddPrisonerAsync(Temporary_Prison.Data.PrisonService.PrisonerDto prisoner) {
            return base.Channel.AddPrisonerAsync(prisoner);
        }
        
        public Temporary_Prison.Data.PrisonService.PrisonerDto[] SearchFilter(System.Nullable<System.DateTime> dateOfDetention, string name, string address) {
            return base.Channel.SearchFilter(dateOfDetention, name, address);
        }
        
        public System.Threading.Tasks.Task<Temporary_Prison.Data.PrisonService.PrisonerDto[]> SearchFilterAsync(System.Nullable<System.DateTime> dateOfDetention, string name, string address) {
            return base.Channel.SearchFilterAsync(dateOfDetention, name, address);
        }
        
        public void EditPrisoner(Temporary_Prison.Data.PrisonService.PrisonerDto prisoner) {
            base.Channel.EditPrisoner(prisoner);
        }
        
        public System.Threading.Tasks.Task EditPrisonerAsync(Temporary_Prison.Data.PrisonService.PrisonerDto prisoner) {
            return base.Channel.EditPrisonerAsync(prisoner);
        }
        
        public void DeletePrisoner(int id) {
            base.Channel.DeletePrisoner(id);
        }
        
        public System.Threading.Tasks.Task DeletePrisonerAsync(int id) {
            return base.Channel.DeletePrisonerAsync(id);
        }
        
        public void RegisterDetention(Temporary_Prison.Data.PrisonService.RegistrationOfDetentionDto registrationOfDetention) {
            base.Channel.RegisterDetention(registrationOfDetention);
        }
        
        public System.Threading.Tasks.Task RegisterDetentionAsync(Temporary_Prison.Data.PrisonService.RegistrationOfDetentionDto registrationOfDetention) {
            return base.Channel.RegisterDetentionAsync(registrationOfDetention);
        }
        
        public void ReleaseOfPrisoner(Temporary_Prison.Data.PrisonService.ReleaseOfPrisonerDto release) {
            base.Channel.ReleaseOfPrisoner(release);
        }
        
        public System.Threading.Tasks.Task ReleaseOfPrisonerAsync(Temporary_Prison.Data.PrisonService.ReleaseOfPrisonerDto release) {
            return base.Channel.ReleaseOfPrisonerAsync(release);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Temporary_Prison.Data.PrisonService.GetDetentionsByPrisonerIdForPagedListResponse Temporary_Prison.Data.PrisonService.IPrisonerService.GetDetentionsByPrisonerIdForPagedList(Temporary_Prison.Data.PrisonService.GetDetentionsByPrisonerIdForPagedListRequest request) {
            return base.Channel.GetDetentionsByPrisonerIdForPagedList(request);
        }
        
        public Temporary_Prison.Data.PrisonService.DetentionPagedListDto[] GetDetentionsByPrisonerIdForPagedList(int Id, int skip, int rowSize, out int totalCount) {
            Temporary_Prison.Data.PrisonService.GetDetentionsByPrisonerIdForPagedListRequest inValue = new Temporary_Prison.Data.PrisonService.GetDetentionsByPrisonerIdForPagedListRequest();
            inValue.Id = Id;
            inValue.skip = skip;
            inValue.rowSize = rowSize;
            Temporary_Prison.Data.PrisonService.GetDetentionsByPrisonerIdForPagedListResponse retVal = ((Temporary_Prison.Data.PrisonService.IPrisonerService)(this)).GetDetentionsByPrisonerIdForPagedList(inValue);
            totalCount = retVal.totalCount;
            return retVal.GetDetentionsByPrisonerIdForPagedListResult;
        }
        
        public System.Threading.Tasks.Task<Temporary_Prison.Data.PrisonService.GetDetentionsByPrisonerIdForPagedListResponse> GetDetentionsByPrisonerIdForPagedListAsync(Temporary_Prison.Data.PrisonService.GetDetentionsByPrisonerIdForPagedListRequest request) {
            return base.Channel.GetDetentionsByPrisonerIdForPagedListAsync(request);
        }
        
        public Temporary_Prison.Data.PrisonService.DetentionDto GetDetentionById(int id) {
            return base.Channel.GetDetentionById(id);
        }
        
        public System.Threading.Tasks.Task<Temporary_Prison.Data.PrisonService.DetentionDto> GetDetentionByIdAsync(int id) {
            return base.Channel.GetDetentionByIdAsync(id);
        }
        
        public void EditDetention(Temporary_Prison.Data.PrisonService.DetentionDto detention) {
            base.Channel.EditDetention(detention);
        }
        
        public System.Threading.Tasks.Task EditDetentionAsync(Temporary_Prison.Data.PrisonService.DetentionDto detention) {
            return base.Channel.EditDetentionAsync(detention);
        }
        
        public void DeleteDetention(int id) {
            base.Channel.DeleteDetention(id);
        }
        
        public System.Threading.Tasks.Task DeleteDetentionAsync(int id) {
            return base.Channel.DeleteDetentionAsync(id);
        }
    }
}
